IF(${OPERATING_SYSTEM} MATCHES linux)# Linux
  SET(MACHINE_ENTRY ${SOURCE_DIR}/machine_constants_linux.f90)
ELSEIF(${OPERATING_SYSTEM} MATCHES aix)#AIX
    SET(MACHINE_ENTRY ${SOURCE_DIR}/machine_constants_aix.f90)
ELSE(${OPERATING_SYSTEM} MATCHES linux)# windows
    SET(MACHINE_ENTRY ${SOURCE_DIR}/machine_constants_windows.f90)
ENDIF(${OPERATING_SYSTEM} MATCHES linux)

FILE(GLOB MACHINE_EXCLUDES "${SOURCE_DIR}" "${SOURCE_DIR}/machine_constants_*.f90")
LIST(REMOVE_ITEM MACHINE_EXCLUDES ${MACHINE_ENTRY})

IF(${USECELLML} MATCHES true)
  SET(CELLML_ENTRY  ${SOURCE_DIR}/cmiss_cellml.f90)
ELSE(${USECELLML} MATCHES true)
  SET(CELLML_ENTRY  ${SOURCE_DIR}/cmiss_cellml_dummy.f90)
ENDIF(${USECELLML} MATCHES true)

FILE(GLOB CELLML_EXCLUDES "${SOURCE_DIR}" "${SOURCE_DIR}/cmiss_cellml*.f90")
LIST(REMOVE_ITEM CELLML_EXCLUDES ${CELLML_ENTRY})

FILE(GLOB FIELDML_EXCLUDES "${SOURCE_DIR}" "${SOURCE_DIR}/fieldml_*.f90")

SET(EXCLUDED_ROUTINES 
  ${SOURCE_DIR}/Helmholtz_TEMPLATE_equations_routines.f90
  ${SOURCE_DIR}/binary_file_f.f90
  ${SOURCE_DIR}/finite_element_routines.f90
  ${SOURCE_DIR}/binary_file_c.c
)
LIST(APPEND EXCLUDED_ROUTINES ${MACHINE_EXCLUDES})
LIST(APPEND EXCLUDED_ROUTINES ${CELLML_EXCLUDES})
IF(NOT ${USEFIELDML} MATCHES true)
  LIST(APPEND EXCLUDED_ROUTINES ${FIELDML_EXCLUDES})
ENDIF(NOT ${USEFIELDML} MATCHES true)