"""OpenCMISS Python Interface
"""

import opencmiss_swig
from utils import *

class CMWrapper(object):
    """Wrap the OpenCMISS python interface generated by SWIG to make
    it more object oriented and "Pythonic"
    """

    def __getattr__(self,attr):
        """Get an OpenCMISS constant, removing the need to
        prefix constants with a CMISS namespace as this is done
        already in Python
        """
        #Constants in Python should be in capitals with underscores, but
        #if we converted to camel-case this would screw up things like
        #CMISSSolverPETScLibrary, so just use camel-case
        try:
            return getattr(opencmiss_swig,'CMISS'+attr)
        except AttributeError:
            raise AttributeError("OpenCMISS has no attribute %r" % (attr))

CMISS = CMWrapper()

WorldCoordinateSystem = call_routine(CMISS.CoordinateSystemTypeInitialise)
WorldRegion = call_routine(CMISS.RegionTypeInitialise)
call_routine(CMISS.Initialise, (WorldCoordinateSystem, WorldRegion))
