MODULE CONSTANTS

  INTEGER(INTG), PARAMETER :: FIRST_VALUE = 1
  INTEGER(INTG), PARAMETER :: SECOND_VALUE = 2
  INTEGER(INTG), PARAMETER :: THIRD_VALUE = 3

  PUBLIC FIRST_VALUE, SECOND_VALUE, THIRD_VALUE

END MODULE CONSTANTS
