# Makefile to build documentations
# TODO doxygen build 
# TODO latex (pdf, html) build
#----------------------------------------------------------------------------------------------------------------------------------

clean:
	find ../../cm -type d -exec chmod 755 {} \;
	rm -rf doxy/latexhtml doxy/doxy doxy/OpenCMISSNotes.pdf

