#!/usr/bin/perl -w

$filename=$ARGV[0];
$maxrank=0;
for($i=0;$i<=9;$i++) {
  $numlines[$i]=0;
}
open(INFILE,"<$filename");
while($inline = <INFILE> ) {
  if(substr($inline,1,1) eq ":") {
    $ranknum=substr($inline,0,1);
    if($ranknum>$maxrank){
      $maxrank=$ranknum;
    }
    $numlines[$ranknum]++;
    $lines[$ranknum][$numlines[$ranknum]]=$inline;
  }
}
close(INFILE);
for($i=0;$i<=$maxrank;$i++) {
  open(OUTFILE,">$filename"."."."$i");
  for($j=1;$j<=$numlines[$i];$j++) {
    print OUTFILE $lines[$i][$j];
  }
  close(OUTFILE);
}
