#ifndef FIELD_EXPORT_CONSTANTS_H
#define FIELD_EXPORT_CONSTANTS_H

#define FIELD_EXPORT_NO_ERROR						0x00000
#define FIELD_EXPORT_ERROR_UNKNOWN_TYPE				0x10001
#define FIELD_EXPORT_ERROR_FILE_IO					0x10002
#define FIELD_EXPORT_ERROR_BAD_HANDLE				0x10003
#define FIELD_EXPORT_ERROR_CLOSED_HANDLE			0x10004
#define FIELD_EXPORT_ERROR_FILE_WRITE				0x10005
#define FIELD_EXPORT_ERROR_UNKNOWN_INTERPOLATION	0x10006
#define FIELD_EXPORT_ERROR_UNKNOWN_LABEL_TYPE		0x10007

#define EXPORT_TYPE_CLOSED 0
#define EXPORT_TYPE_FILE   1

#endif