#ifndef FIELD_EXPORT_CONSTANTS_H
#define FIELD_EXPORT_CONSTANTS_H

#define FIELD_EXPORT_NO_ERROR						00000
#define FIELD_EXPORT_ERROR_UNKNOWN_TYPE				10001
#define FIELD_EXPORT_ERROR_FILE_IO					10002
#define FIELD_EXPORT_ERROR_BAD_HANDLE				10003
#define FIELD_EXPORT_ERROR_CLOSED_HANDLE			10004
#define FIELD_EXPORT_ERROR_FILE_WRITE				10005
#define FIELD_EXPORT_ERROR_UNKNOWN_INTERPOLATION	10006
#define FIELD_EXPORT_ERROR_UNKNOWN_LABEL_TYPE		10007

#define EXPORT_TYPE_CLOSED 0
#define EXPORT_TYPE_FILE   1

#endif