!> This module handles all Kalman filtering problem routines.
!> reference to Laplace_equation_routines.f90
MODULE OPTIMISATION_KALMAN_ROUTINES
  USE BASE_ROUTINES
  USE BASIS_ROUTINES
  USE BOUNDARY_CONDITIONS_ROUTINES
  USE CONSTANTS
  USE CONTROL_LOOP_ROUTINES
  USE DISTRIBUTED_MATRIX_VECTOR
  USE DOMAIN_MAPPINGS
  USE EQUATIONS_ROUTINES
  USE EQUATIONS_MAPPING_ROUTINES
  USE EQUATIONS_MATRICES_ROUTINES
  USE EQUATIONS_SET_CONSTANTS
  USE FIELD_ROUTINES
  USE INPUT_OUTPUT
  USE ISO_VARYING_STRING
  USE KINDS
  USE MATRIX_VECTOR
  USE NODE_ROUTINES
  USE PROBLEM_CONSTANTS
  USE STRINGS
  USE SOLVER_ROUTINES
  USE TIMER
  USE TYPES

  IMPLICIT NONE

  PRIVATE

  !Module parameters

  !Module types

  !Module variables

  !Interfaces
  
  PUBLIC OPTIMISATION_KALMAN_PROBLEM_SETUP, OPTIMISATION_KALMAN_PROBLEM_SAMPLING_SUBTYPE_SETUP, &
      &  OPTIMISATION_KALMAN_PROBLEM_SUBTYPE_SET
  
CONTAINS


  !
  !================================================================================================================================
  !

  !>Sets up the Kalman filtering problem.
  !>reference to LAPLACE_EQUATION_PROBLEM_SUBTYPE_SET
  SUBROUTINE OPTIMISATION_KALMAN_PROBLEM_SETUP(PROBLEM,PROBLEM_SETUP,ERR,ERROR,*)

    !Argument variables
    TYPE(PROBLEM_TYPE), POINTER :: PROBLEM !<A pointer to the problem set to setup a Laplace equation on.
    TYPE(PROBLEM_SETUP_TYPE), INTENT(INOUT) :: PROBLEM_SETUP !<The problem setup information
    INTEGER(INTG), INTENT(OUT) :: ERR !<The error code
    TYPE(VARYING_STRING), INTENT(OUT) :: ERROR !<The error string
    !Local Variables
    TYPE(VARYING_STRING) :: LOCAL_ERROR
    
    CALL ENTERS("OPTIMISATION_KALMAN_PROBLEM_SETUP",ERR,ERROR,*999)

    IF(ASSOCIATED(PROBLEM)) THEN
      SELECT CASE(PROBLEM%SUBTYPE)
      CASE(PROBLEM_OPTIMISATION_KALMAN_SAMPLING_SUBTYPE)
        CALL OPTIMISATION_KALMAN_PROBLEM_SAMPLING_SUBTYPE_SETUP(PROBLEM,PROBLEM_SETUP,ERR,ERROR,*999)
      CASE(PROBLEM_OPTIMISATION_KALMAN_UKF_SUBTYPE)
        CALL FLAG_ERROR("Not implemented.",ERR,ERROR,*999)
      CASE DEFAULT
        LOCAL_ERROR="Problem subtype "//TRIM(NUMBER_TO_VSTRING(PROBLEM%SUBTYPE,"*",ERR,ERROR))// &
          & " is not valid for a Kalma type of a optimisation problem class."
        CALL FLAG_ERROR(LOCAL_ERROR,ERR,ERROR,*999)
      END SELECT
    ELSE
      CALL FLAG_ERROR("Problem is not associated.",ERR,ERROR,*999)
    ENDIF
       
    CALL EXITS("OPTIMISATION_KALMAN_PROBLEM_SETUP")
    RETURN
999 CALL ERRORS("OPTIMISATION_KALMAN_PROBLEM_SETUP",ERR,ERROR)
    CALL EXITS("OPTIMISATION_KALMAN_PROBLEM_SETUP")
    RETURN 1
  END SUBROUTINE OPTIMISATION_KALMAN_PROBLEM_SETUP

  !
  !================================================================================================================================
  !

  !>Sets up a simple sampling subtype of Kalman problem.
  !>reference to LAPLACE_EQUATION_PROBLEM_STANDARD_SETUP
  SUBROUTINE OPTIMISATION_KALMAN_PROBLEM_SAMPLING_SUBTYPE_SETUP(PROBLEM,PROBLEM_SETUP,ERR,ERROR,*)

    !Argument variables
    TYPE(PROBLEM_TYPE), POINTER :: PROBLEM !<A pointer to the problem to setup
    TYPE(PROBLEM_SETUP_TYPE), INTENT(INOUT) :: PROBLEM_SETUP !<The problem setup information
    INTEGER(INTG), INTENT(OUT) :: ERR !<The error code
    TYPE(VARYING_STRING), INTENT(OUT) :: ERROR !<The error string
    !Local Variables
    TYPE(CONTROL_LOOP_TYPE), POINTER :: CONTROL_LOOP,CONTROL_LOOP_ROOT
    TYPE(SOLVER_TYPE), POINTER :: SOLVER
    TYPE(SOLVER_EQUATIONS_TYPE), POINTER :: SOLVER_EQUATIONS
    TYPE(SOLVERS_TYPE), POINTER :: SOLVERS
    TYPE(VARYING_STRING) :: LOCAL_ERROR
    
    CALL ENTERS("OPTIMISATION_KALMAN_PROBLEM_SAMPLING_SUBTYPE_SETUP",ERR,ERROR,*999)

    NULLIFY(CONTROL_LOOP)
    NULLIFY(SOLVER)
    NULLIFY(SOLVER_EQUATIONS)
    NULLIFY(SOLVERS)
    IF(ASSOCIATED(PROBLEM)) THEN
      IF(PROBLEM%SUBTYPE==PROBLEM_OPTIMISATION_KALMAN_SAMPLING_SUBTYPE) THEN
       SELECT CASE(PROBLEM_SETUP%SETUP_TYPE)
        !TODO
        !reference to LAPLACE_EQUATION_PROBLEM_STANDARD_SETUP() in Laplace_equations_routines.f90

       CASE DEFAULT
          CALL FLAG_ERROR("OPTIMISATION_KALMAN_PROBLEM_SAMPLING_SUBTYPE_SETUP not impelmented yet.",ERR,ERROR,*999)
          LOCAL_ERROR="The setup type of "//TRIM(NUMBER_TO_VSTRING(PROBLEM_SETUP%SETUP_TYPE,"*",ERR,ERROR))// &
            & " is invalid for a sampling subtype problem of Kalman type."
          CALL FLAG_ERROR(LOCAL_ERROR,ERR,ERROR,*999)
        END SELECT
      ELSE
        LOCAL_ERROR="The problem subtype of "//TRIM(NUMBER_TO_VSTRING(PROBLEM%SUBTYPE,"*",ERR,ERROR))// &
          & " does not equal a Kalman sampling subtype."
        CALL FLAG_ERROR(LOCAL_ERROR,ERR,ERROR,*999)
      ENDIF
    ELSE
      CALL FLAG_ERROR("Problem is not associated.",ERR,ERROR,*999)
    ENDIF
       
    CALL EXITS("OPTIMISATION_KALMAN_PROBLEM_SAMPLING_SUBTYPE_SETUP")
    RETURN
999 CALL ERRORS("OPTIMISATION_KALMAN_PROBLEM_SAMPLING_SUBTYPE_SETUP",ERR,ERROR)
    CALL EXITS("OPTIMISATION_KALMAN_PROBLEM_SAMPLING_SUBTYPE_SETUP")
    RETURN 1
  END SUBROUTINE OPTIMISATION_KALMAN_PROBLEM_SAMPLING_SUBTYPE_SETUP
  
  !
  !================================================================================================================================
  !

  !>Sets/changes the problem subtype for a Laplace equation type .
  SUBROUTINE OPTIMISATION_KALMAN_PROBLEM_SUBTYPE_SET(PROBLEM,PROBLEM_SUBTYPE,ERR,ERROR,*)

    !Argument variables
    TYPE(PROBLEM_TYPE), POINTER :: PROBLEM !<A pointer to the problem to set the problem subtype for
    INTEGER(INTG), INTENT(IN) :: PROBLEM_SUBTYPE !<The problem subtype to set
    INTEGER(INTG), INTENT(OUT) :: ERR !<The error code
    TYPE(VARYING_STRING), INTENT(OUT) :: ERROR !<The error string
    !Local Variables
    TYPE(VARYING_STRING) :: LOCAL_ERROR
    
    CALL ENTERS("OPTIMISATION_KALMAN_PROBLEM_SUBTYPE_SET",ERR,ERROR,*999)
    
    IF(ASSOCIATED(PROBLEM)) THEN
      SELECT CASE(PROBLEM_SUBTYPE)
      CASE(PROBLEM_OPTIMISATION_KALMAN_SAMPLING_SUBTYPE)        
        PROBLEM%CLASS=PROBLEM_OPTIMISATION_CLASS
        PROBLEM%TYPE=PROBLEM_OPTIMISATION_KALMAN_TYPE
        PROBLEM%SUBTYPE=PROBLEM_OPTIMISATION_KALMAN_SAMPLING_SUBTYPE     
      CASE(PROBLEM_OPTIMISATION_KALMAN_UKF_SUBTYPE)
        CALL FLAG_ERROR("Not implemented.",ERR,ERROR,*999)
      CASE DEFAULT
        LOCAL_ERROR="Problem subtype "//TRIM(NUMBER_TO_VSTRING(PROBLEM_SUBTYPE,"*",ERR,ERROR))// &
          & " is not valid for a Laplace equation type of a classical field problem class."
        CALL FLAG_ERROR(LOCAL_ERROR,ERR,ERROR,*999)
      END SELECT
    ELSE
      CALL FLAG_ERROR("Problem is not associated.",ERR,ERROR,*999)
    ENDIF
       
    CALL EXITS("OPTIMISATION_KALMAN_PROBLEM_SUBTYPE_SET")
    RETURN
999 CALL ERRORS("OPTIMISATION_KALMAN_PROBLEM_SUBTYPE_SET",ERR,ERROR)
    CALL EXITS("OPTIMISATION_KALMAN_PROBLEM_SUBTYPE_SET")
    RETURN 1
  END SUBROUTINE OPTIMISATION_KALMAN_PROBLEM_SUBTYPE_SET

  !
  !================================================================================================================================

END MODULE OPTIMISATION_KALMAN_ROUTINES